### ISSUE TITLE
Commit access to gitscm

### ISSUE THREAD

**Issue by mjg** [git/gitscm-old#17]
Can we please have more people with commit access to gitscm, pushing to gitscm.com?

There are 10 pull requests and 11 issues with a huge lag. gitscm.com seems to be the first place many people hit, so it should be up to date. It links to the "git community" (git mailing list) but it's hard for that community to get involved, the way it currently is.

The alternative is forking (again) and finding a new domain, of course, but let's not go there.

**Comment by schacon** [comment]
Yeah - some of those PRs I do need to pull and deploy, others I need
to close because I'm not going to pull them.

The main issue is that I've started a redesign of the site to help
address most or all of these issues, but the going has been slow.
Because of this, however, I've been falling behind on keeping the site
more up to date.  I have also gotten a huge number or requests about
failing kernel.org links from people thinking git-scm was having
problems.  I'm considering if I need to purge the site of k.org links
until it comes back.  I also need to put the Survey link up.

Perhaps I can get to some of this today.

On Wed, Sep 21, 2011 at 3:22 AM, Michael J Gruber
reply@reply.github.com
wrote:

**Comment by schacon** [comment]
i suppose i should probably ask the ML to see if anyone else wants to share the responsibility.  The problem is that not many of the Git guys I know well (ie: met at a gittogether) are big web guys.  I may be able to rope @matthewmccullough into some blog help, which would be good.

Are you volunteering?

**Comment by matthewmccullough** [comment]
Rope me in.  I'll help with the blog.
